/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ir.h76.hamid;
import java.text.NumberFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JLabel;
/**
 *
 * @author A.I
 */
public class Main extends javax.swing.JFrame {
    Bitcoin bcPrice;
    int usdInT = 15000;
    int gfBitcoins = 30;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
           
        
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bitCoinPriceText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bitCoinPriceLabel = new javax.swing.JLabel();
        gfCountBitcoinText = new javax.swing.JLabel();
        gfBitCoins = new javax.swing.JLabel();
        gfFoolishText = new javax.swing.JLabel();
        gfFoolishPrice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bitCoinPriceText1 = new javax.swing.JLabel();
        usdInTooman = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(200, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("پروژه‌ی محاسبه‌ی حماقت دوست‌دختر");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("توجه: قیمت بیت‌کوین هر  ۲ ثانیه به روز می‌شود، اعداد واقعی هستند");

        bitCoinPriceText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bitCoinPriceText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bitCoinPriceText.setText("قیمت هر بیت‌کوین در این لحظه به دلار آمریکا");

        bitCoinPriceLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bitCoinPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bitCoinPriceLabel.setText("Loading...");

        gfCountBitcoinText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gfCountBitcoinText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gfCountBitcoinText.setText("تعداد احتمالی بیت‌کوین‌های دوست‌دختر");

        gfBitCoins.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gfBitCoins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gfBitCoins.setText("30");

        gfFoolishText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gfFoolishText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gfFoolishText.setText("محاسبه‌ی هزینه‌ی حماقت دوست دختر در این لحظه");

        gfFoolishPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gfFoolishPrice.setForeground(new java.awt.Color(255, 0, 0));
        gfFoolishPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gfFoolishPrice.setText("Loading...");

        jLabel3.setForeground(new java.awt.Color(150, 150, 150));
        jLabel3.setText("Story From: tdvlpr | Idea, Design & Programming: Hamid0x4c");

        bitCoinPriceText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bitCoinPriceText1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bitCoinPriceText1.setText("قیمت دلار آمریکا به تومان - حدوداً");

        usdInTooman.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usdInTooman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usdInTooman.setText(usdInT + "");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(gfFoolishPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gfFoolishText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bitCoinPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usdInTooman, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gfBitCoins, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(bitCoinPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bitCoinPriceText1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gfCountBitcoinText, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bitCoinPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bitCoinPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usdInTooman)
                    .addComponent(bitCoinPriceText1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gfCountBitcoinText)
                    .addComponent(gfBitCoins))
                .addGap(11, 11, 11)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gfFoolishText)
                    .addComponent(gfFoolishPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HTTPClient client = new HTTPClient();                
                Timer timer = new Timer();
                timer.schedule(new TimerTask() {
                    @Override
                    public void run() {
                        bcPrice = client.getData();
                        bitCoinPriceLabel.setText(bcPrice.getPrice() + " دلار");
                        
                        
                        long calculatedPrice = (long) (bcPrice.getPrice() * usdInT) * gfBitcoins;
                        
                        // format number in three digit
                        NumberFormat myFormat = NumberFormat.getInstance();
                        myFormat.setGroupingUsed(true);
                        
                        String foolishText = myFormat.format(calculatedPrice) + " تومان";
                        gfFoolishPrice.setText(foolishText);
                    }
                }, 0, client.myLong);
            }
        });
        
    }// </editor-fold>
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Main myPanel = new Main();
        myPanel.setLocationRelativeTo(null);
        myPanel.setVisible(true);
        myPanel.setResizable(false);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel bitCoinPriceLabel;
    private javax.swing.JLabel bitCoinPriceText;
    private javax.swing.JLabel bitCoinPriceText1;
    private javax.swing.JLabel gfBitCoins;
    private javax.swing.JLabel gfCountBitcoinText;
    private javax.swing.JLabel gfFoolishPrice;
    private javax.swing.JLabel gfFoolishText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel usdInTooman;
    // End of variables declaration                   
}
